### PR TITLE
feat: github publishing backend.

### PR DESCRIPTION
**Pull request by zicklag**
- Includes addition of daisyui component plugin.

This doesn't finish the GitHub publishing implementation, but since I ended up adding the DaisyUI components and some other minor re-organization changes, I wanted to get review on this as early as possible so I don't cause conflicts or other issues.

### CODE REVIEW

**Comment by zicklag** [comment]
Screenshots:

image

image

This is the last page, which is incomplete, and I will finish it in the next PR if this all looks good to you:

image

**Comment by krivahtoo** [comment]
Is it currently, possible to log in to GitHub?

**Comment by zicklag** [comment]
Yep, GitHub login is working great. I think I'm pretty close to finishing off publishing functionality too.

**Comment by krivahtoo** [comment]
Okay, How do I log in? I am seeing only a blank page.
2023-05-30-063549_504x604_scrot

**Comment by zicklag** [comment]
Ah, yeah, I forgot about that, and I forgot to update the `.env.sample` file, which is inaccurate now.

The client ID isn't secret so you could use this for the `.env` file to use my temporary test OAuth app:

```
PUBLIC_GH_CLIENT_ID=e94457f9257592a74a8c
```

**Comment by krivahtoo** [comment]
> That and I have to figure out why the .env file...

I think a Client ID can be directly embedded into the app (if it is not a secret), instead of using `.env`. Unless there is a specific reason to use `.env` or can be preloaded by Svelte at built time.

**Comment by zicklag** [comment]
Good point, I just put the client ID directly in the `config.ts` so there won't be any special dev setup.

I think that fixes everything other than the CI issue on windows, which I still haven't verified if that is caused by this PR or something external to the codebase changed, like a crate version or something.

**Comment by zicklag** [comment]
There we go, I fixed CI by updating some crates and this should be ready to go!

**Pull request merged**
