### PR TITLE
refactor: adopt new docker compose specifications

### PR DESCRIPTION
**Pull request by azzamsa**

### CODE REVIEW

**Comment by azzamsa** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by zicklag** [comment]
What is the reason for removing the version? Doesn't that make it go back to the old pre-2.0 version of the compose format?

**Comment by secondtruth** [comment]
> What is the reason for removing the version? Doesn't that make it go back to the old pre-2.0 version of the compose format?

`version` is obsolete now. `docker compose up` throws a warning if it is used.

**Comment by azzamsa** [comment]
> Technically you can still define it… But you will get the warning you observed, and it won’t be used, as docker compose v2 (=the cli plugin) will always use the latest version of the compose file schema. -- Metin Y.Leader

From [Docker-compose.yml: `version` is obsolete - Docker Hub - Docker Community Forums](https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313/2)

**Pull request merged**
