### PR TITLE
fix: publicly accesible mastodon access token through iroh

### PR DESCRIPTION
**Pull request by kimlimjustin**
As the user profile is accessible publicly through Iroh, this makes mastodon_access_token accessible to everyone. This PR sets every mastodon_access_token to Null and substitute the usage of mastodon_access_token

### CODE REVIEW

**Comment by zicklag** [comment]
Can you add something [here](https://github.com/commune-os/weird/blob/81ee997ea3dbd52bfcfa889d725833ee3ef34ecb/backend/weird/src/lib.rs#L92), that loops through all the profiles ( see [here](https://github.com/commune-os/weird/blob/81ee997ea3dbd52bfcfa889d725833ee3ef34ecb/backend/weird/src/profile.rs#L530-L535) for how to list profiles ), and then for each profile sets the mastodon token to Null?

That way users don't have to go in and save their profile to clean up the token.

**Comment by kimlimjustin** [comment]
Updated the code, could you please check if it's correct or not as I'm not that familiar to Iroh

**Review by zicklag — APPROVED** [review]
Looks good!

**Comment by zicklag** [comment]
I'm going to try and deploy this later today.

**Pull request merged**
